from .detection_trainer import DetectionTrainer
from .detection_evaluator import DetectionEvaluator

from .classification_trainer import ClassificationTrainer
from .classification_evaluator import ClassificationEvaluator
